### PR TITLE
Upgrade bootstrap

### PR DESCRIPTION
**Pull request by antonmolodykh**
* Updates bootstrap
* Replaces icons with `fontawesome`
* Removes unused js/css
* Replaces icons in `bootstrap-datepicker.js` and `bootstrap-timepicker.js`. Alternatively, I could replace these plugins with a newer `tempusdominus-bootstrap-4.js` but I think there's no sense to do it just to replace the icons.

Refs #840 #816

### CODE REVIEW

**Comment by vpetersson** [comment]
Nice! Can you post some screenshots?

**Comment by antonmolodykh** [comment]
image
image
image
image

a last picture - hover effect for a button

**Comment by antonmolodykh** [comment]
image
image

**Comment by vpetersson** [comment]
@antonmolodykh see https://app.codacy.com/app/vpetersson/screenly-ose/pullRequest?prid=1848026

**Comment by antonmolodykh** [comment]
@vpetersson Codacy sees problems with fontawesome files and coffeescript-generated files

**Pull request merged**
