### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ealmonte32**
minor update for celery and ansible

### CODE REVIEW

**Comment by ealmonte32** [comment]
I dont know why travis is giving error on the redis/celery part, if I am running these updated versions and redis connects fine:
```

pi@screenlypi:~ $ sudo pip list | grep redis
redis                        3.3.11
pi@screenlypi:~ $ sudo pip list | grep celery
celery                       4.4.0
pi@screenlypi:~ $

pi@screenlypi:~ $ journalctl | grep -i celery
Jan 13 17:54:13 screenlypi systemd[1]: Started Screenly celery worker.
Jan 13 17:54:20 screenlypi celery[408]: [2020-01-13 17:54:20,613: INFO/Beat] beat: Starting...
Jan 13 17:54:21 screenlypi celery[408]: [2020-01-13 17:54:21,166: INFO/MainProcess] Connected to redis://localhost:6379/0
Jan 13 17:54:21 screenlypi celery[408]: [2020-01-13 17:54:21,206: INFO/MainProcess] mingle: searching for neighbors
Jan 13 17:54:22 screenlypi celery[408]: [2020-01-13 17:54:22,299: INFO/MainProcess] mingle: all alone
Jan 13 17:54:22 screenlypi celery[408]: [2020-01-13 17:54:22,451: INFO/MainProcess] worker@screenly ready.
pi@screenlypi:~ $

```

**Comment by vpetersson** [comment]
Travis seems to be failing @ealmonte32.

**Comment by rusko124** [comment]
@ealmonte32 Did you test how celery worker works after updating kombu to 4.6.7?
I have issue before with this.
Use `celery -A server.celery status` for testing.
Response should be: `worker@screenly: OK`

**Comment by ealmonte32** [comment]
> @ealmonte32 Did you test how celery worker works after updating kombu to 4.6.7?
> I have issue before with this.
> Use `celery -A server.celery status` for testing.
> Response should be: `worker@screenly: OK`

Maybe I am doing something wrong? I dont know much about celery but even after downgrading kombu to 4.6.3 I still get this error:


```
pi@screenlypi3:~ $ sudo pip list | grep "celery\|kombu"
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
celery                  4.3.0      
kombu                   4.6.3      
WARNING: You are using pip version 20.0.1; however, version 20.0.2 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
pi@screenlypi3:~ $ celery -A server.celery status
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 290, in execute_from_commandline
    self.on_error(UNABLE_TO_LOAD_APP_MODULE_NOT_FOUND.format(e.name))
AttributeError: 'exceptions.ImportError' object has no attribute 'name'
pi@screenlypi3:~ $ 


```

**Comment by vpetersson** [comment]
I think you're in the wrong directory. You need to stand in the OSE directory to launch celery.

**Comment by ealmonte32** [comment]
> I think you're in the wrong directory. You need to stand in the OSE directory to launch celery.

Ok, got it, thanks, here is result from celery, so it looks fine to me:
```
pi@screenlypi:~ $ cd ./screenly
pi@screenlypi:~/screenly $ celery -A server.celery status
worker@screenly: OK

1 node online.
pi@screenlypi:~/screenly $ sudo pip list | grep "celery\|kombu"
celery                       4.3.0
kombu                        4.6.7
```

Looking at the travis logs, it didn't fail because of celery/kombu though, it's saying ansible is not installed, which is true since it was removed from requirements, but it is called for install in `install.sh` before ansible-playbook is ran..
From Travis CI build fail:
```
The program 'ansible-playbook' is currently not installed. To run 'ansible-playbook' please ask your administrator to install the package 'ansible'
The command "ansible-playbook --syntax-check -i ansible/localhost ansible/site.yml" exited with 127.
```

See, you dont install ansible on travis.yml before running the playbook:
```
install:
  - pip install -U pip
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requirements.dev.txt
```
But if you installed ansible there after `pip`, which installs before running the playbook like in the `install.sh` script, then you would be fine.. *(the run_upgrade.sh calls the master install.sh script anyway so you dont need to edit that file)*
___
```
sudo pip install ansible==2.8.2

sudo -u pi ansible localhost -m git -a "repo=$REPOSITORY dest=/home/pi/screenly version=$BRANCH"
cd /home/pi/screenly/ansible

sudo -E ansible-playbook site.yml $EXTRA_ARGS
```
This is on `install.sh`, so as you can see, you are installing ansible prior to calling the playbook which is probably the best way to do it because while ansible is considered a requirement, it doesnt need to be in the requirements file, it can be in the main installer as a main requirement that doesnt depend on a requirements.txt file being called..

What do you think?

**Comment by ealmonte32** [comment]
@vpetersson 
If you want to have the same version install on both during install.sh and in requirements.txt then what else besides this can we do:

```
sudo pip install $(curl -s https://raw.githubusercontent.com/Screenly/screenly-ose/master/requirements/requirements.txt | grep "ansible" | cat)
```
This always returns the exact version you have in requirements, thus avoid a conflict of version..

**Comment by ealmonte32** [comment]
Currently testing all the updates for requirements:
image

**Comment by ealmonte32** [comment]
Closing.. Will just let rusko to update packages since he knows which ones are exactly needed for the viewer and the imports... this has been getting too unorganized for me to keep up updating some and testing then updating and testing one package at a time.. Was trying to make sure the packages were updated since some include various improvements and fixes based on release notes.

**Pull request closed without merging**
