### PR TITLE
Add default loop times

### PR DESCRIPTION
**Pull request by rusko124**
#119 
screen_1
screen_2
screen_3

### CODE REVIEW

**Comment by vpetersson** [comment]
@rusko124 Good progress. Could you make some changes:

* Change  "Date" to "Play for" 
* Make it a drop-down (with "30 days" being the default)
* Change "Range" to "Manual"
* Hide the start and end date when Manual is not selected
* Add "1 year" and "Forever" (where "Forever" is just a date really far into the future)

**Comment by rusko124** [comment]
@vpetersson 
I make edits, check them pls.
screen_4
screen_5

**Comment by vpetersson** [comment]
Ys, just missing the drop-down in the screenshot.

**Comment by rusko124** [comment]
@vpetersson 
Something like this?
screen_7
screen_8
screen_9

**Pull request merged**
