### PR TITLE
added docker-compose.yml

### PR DESCRIPTION
**Pull request by Kipjr**
Created docker-compose file with dependencies:

- Server first
- Websocket second
- Viewer last

### CODE REVIEW

**Comment by vpetersson** [comment]
@Kipjr Looks like this is missing some dependencies. Take a look at [docker-compose.yml](https://github.com/Screenly/screenly-ose/blob/master/docker-compose.yml) in master.

**Comment by Kipjr** [comment]
viewer and server both seems to be working:
image

**Comment by vpetersson** [comment]
@Kipjr You need to bring in Celery and Redis too. If not, the background task processing will not work. I'm not 100% sure this is hooked up into this branch yet, but it is a precursor to merging the branches.

**Comment by Kipjr** [comment]
Got Redis and Celery container almost working except for one annoying error. I suspect it has to do with the last line in the Dockerfile.celery. Any suggestions? 
```

screenly-ose-celery       |   from cryptography import x509
screenly-ose-celery       | Traceback (most recent call last):
screenly-ose-celery       |   File "/usr/local/bin/celery", line 8, in <module>
screenly-ose-celery       |     sys.exit(main())
screenly-ose-celery       |   File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 16, in main
screenly-ose-celery       |     _main()
screenly-ose-celery       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 322, in main
screenly-ose-celery       |     cmd.execute_from_commandline(argv)
screenly-ose-celery       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
screenly-ose-celery       |     super(CeleryCommand, self).execute_from_commandline(argv)))
screenly-ose-celery       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 290, in execute_from_commandline
screenly-ose-celery       |     self.on_error(UNABLE_TO_LOAD_APP_MODULE_NOT_FOUND.format(e.name))
screenly-ose-celery       | AttributeError: 'exceptions.ImportError' object has no attribute 'name'
```
**Docker-compose / Celery:**
```

  screenly-ose-celery:
    container_name: "screenly-ose-celery"
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - screenly-ose-redis
      - screenly-ose-server
    environment:
      - CELERY_BROKER_URL=redis://screenly-ose-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://screenly-ose-redis:6379/0
    image: screenly-ose-celery
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro    
      - ./:/home/pi/screenly:ro
      - screenly-assets-volume:/home/pi/screenly_assets
      - screenly-volume:/home/pi/.screenly
```


**Dockerfile.celery:**

```
FROM balenalib/raspberry-pi:stretch

RUN apt-get update && \
    apt-get -y install \
        build-essential \
        curl \
        ffmpeg \
        git-core \
        libffi-dev \
        libssl-dev \
        omxplayer  \
        net-tools \
        procps \
        python-dev \
        python-gobject \
        python-pil \
        python-netifaces \
        python-simplejson \
		python-cryptography \
        sqlite3 \
    && \
    apt-get clean

# Install Python requirements
ADD requirements.txt /tmp/requirements.txt
ADD requirements.celery.txt /tmp/requirements.celery.txt
RUN curl -s https://bootstrap.pypa.io/get-pip.py | python
RUN pip install --upgrade pip --use-feature=2020-resolver 
RUN pip install -r /tmp/requirements.txt --use-feature=2020-resolver 
RUN pip install -r /tmp/requirements.celery.txt --use-feature=2020-resolver 

RUN useradd pi

RUN mkdir -p /home/pi/.screenly /home/pi/screenly /home/pi/screenly_assets
RUN chown -R pi:pi /home/pi/.screenly /home/pi/screenly_assets

USER pi
WORKDIR /home/pi/screenly

# https://stackoverflow.com/questions/19577172/celery-worker-error-importerror-no-module-named-celery
CMD celery --app server.celery_app worker -B -n worker@screenly --loglevel=info --schedule /tmp/celerybeat-schedule 
```

**Comment by vpetersson** [comment]
@Kipjr Nice. I spent some cycles yesterday cleaning up docker-compose and bring things up to date. You can find the PR here:
https://github.com/Screenly/screenly-ose/pull/1403

**Comment by ealmonte32** [comment]
@Kipjr 
how are you building your redis image? can i see the dockerfile template?
i was getting the same celery error when testing and forgot if it was a dependency library/module issue or something else..

i havent tested this much but it's my redis dockerfile template:
```
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.12-run
RUN apk add --update redis && rm -rf /var/cache/apk/*
COPY tests/config/redis.conf /etc/redis/redis.conf
CMD ["redis-server", "/etc/redis/redis.conf"]
```

the config file is because i was getting a protected-mode error so i specifically turned it off since only the host can access the redis container as far as i read..
```
# Redis configuration file specifically for balena/docker.
# Service accessible fully by host.
protected-mode no
port 6379
timeout 0
tcp-keepalive 300
supervised auto
loglevel notice
logfile ""
```

**Comment by Kipjr** [comment]
I've found the issue. It is the CMD in Dockerfile.celery. after testing and changing celery/bin/base.py I could find the real error message:

`celery --app sCreenly.thisisatest

Error:
Unable to load celery application.
The module No module named sCreenly was not found.
`

I will post the Dockerfile when I'm back home

**Comment by Kipjr** [comment]
Truncated due to smartphone as shell

```
FROM debian:buster                                          
RUN apt-get update && \                                         
apt-get -y install \                                            
sudo \                                                      
nano \                                                      
bash \                                                      
build-essential \                                           
curl \                                                      
ffmpeg \                                                    
git \                                                       
libffi-dev \                                                
libssl-dev \                                                
mplayer   \                                                 
net-tools \                                                 
procps \                                                    
python-dev \                                                
python-gobject \                                            
python-setuptools \                                         
python-pip \                                                
python-pil \                                                
python-netifaces \
        python-simplejson \                                         
python-cryptography \                                       
sqlite3 \
...
RUN pip install --no-cache-dir -r /tmp/requirements.celery
...
CMD celery --app worker server.celery -B -n worker@screenly --loglevel=verbose --schedule /tmp/celerybeat-schedule
```
Requirements

```
#amqp #here rrdis is used                                   
ansible==2.8.8                                              
argparse==1.2.1                                             
billiard #required
celery[gevent,redis]==4.3.0 #required due to kombu. 
certifi==2020.6.20                 
cffi==1.13.2                                                
click==7.1.2 #6.7                                           
cryptography==3.2                                  
flask_restful==0.3.6                                        
Flask-Cors==3.0.4                                           
flask-restful-swagger-2==0.35                              
flask-swagger-ui==3.0.12                                   
futures==3.0.5                                            
gevent-websocket==0.10.1     
gevent==1.2.2                                              
gunicorn==19.8.1                                           
hurry.filesize==0.9                                         
Jinja2==2.11.2 #2.10.1                                      
kombu==4.6.3  #required, cause of downgrade https://github.
Mako==0.7.3                                                 
MarkupSafe==1.1.1 #1.0        
mixpanel==4.3.2                                            
netifaces==0.10.4                                         
psutil==5.6.7                                              
pyasn1==0.1.8
yOpenSSL==19.1.0                                           
python-dateutil==2.4.2                                      
pytz==2012d                                                 
pyzmq==19.0.2                                               
redis==3.2.0              
requests[security]==2.22.0                                  
sh==1.8                                                     
six==1.11.0                                                 
uptime==2.0.2                                               
urllib3==1.22                                               
vine==1.3.0                                                 
werkzeug== 1.0.1 #0.15.3                  
youtube_dl>=2020.9.20



```

**Comment by Kipjr** [comment]
Add this to docker-compose / celery / environments


```
      - HOME=/data
      - PYTHONPATH=/data/screenly
      - SCREENLYSERVICE=celery
```

Now it only misses /data/.screenly/screenly.conf

**Comment by vpetersson** [comment]
Thanks @Kipjr. @rusko124 is currently working on this and will bring in these changes in https://github.com/Screenly/screenly-ose/pull/1239.

**Comment by vpetersson** [comment]
Closing this out. Lots of changes have been made to this recently.

**Pull request closed without merging**
