### PR TITLE
Assisted 2to3 run

### PR DESCRIPTION
**Pull request by ekevoo**
This is a first-pass attempt to address issue #1091.

I have run most `2to3` fixes on the codebase. I skipped `ws_comma` (seems pointless), `import` (sometimes breaks when `__name__ == '__main__'`), and `basestring` (we want `bytes` instead of `str` in those cases). About half of the rules yielded no changes, which is a good sign.

I did not actually *run* the code. I see there are three active branches and I don't know which one is the best one to do this work on, so I did the low hanging fruit effort and just walked through what `2to3` does, using my previous upgrading experience.

Therefore, this PR is mostly informational and probably incomplete- please check the diffs in the individual commits to see the scope of this migration effort. Something like this is *definitely* the first step in addressing #1091.

### CODE REVIEW

**Comment by ekevoo** [comment]
I don't know why I wrote `fix -m` in the last one… it was `2to3 -f` as well :)

I checked Travis, most errors are due to the new py3 metaclass syntax. The other one is a style problem which is trivial to fix.

**Comment by vpetersson** [comment]
Very nice @ekevoo! Let's get those tests working and then @rusko124 can do a review.

**Comment by rusko124** [comment]
Hey @ekevoo !
Thanks for the work! Can you update the python version for `.travis.yml`, please? First of all I would like to ci passed.

**Comment by ekevoo** [comment]
HFS this is Ubuntu Precise! It has python 3.3! Both of which went out of support 2 years ago.

I'll keep trying some more, but honestly, I can't embrace all this techincal debt :(

**Comment by ekevoo** [comment]
Uh, I don't know where I got precise from. It's trusty, still a bit old but still in support. Python 3.0-3.4 are all kinda not used a lot anymore, and 3.5 is going down soon. I'm going to upgrade past xenial to bionic and see what happens.

**Comment by ekevoo** [comment]
alright, proper runtime errors now!

i know what to do about the bytes/str ones, which i'll get around to some other day, but no promises about the ones that parse html. 🤷‍♂

**Comment by vpetersson** [comment]
Awesome. Good job @ekevoo.

**Comment by ekevoo** [comment]
...and this is all I got for now, which is clearly not enough. I'm not sure how to test the code because I've just been using the prebuilt image and I don't really have a spare pi I can take off and mess with. How would you suggest me to test this using a local amd64 Debian/Ubuntu VM?

**Comment by ekevoo** [comment]
Alright! At least I got python 3.7 running now, which is important because that's the default python 3 version for raspbian buster. I added some end-of-life dates to `.travis.yml` while at that.

This is all I know to do. 🤷‍♂

**Comment by ekevoo** [comment]
Huh? The PR used to only be rejected by Travis and now all three are rejecting it? :(

None of the things Codacy is pointing out were made by me. And I'm not permitted into snyk, but judging by the open branches by dependency-bot I have a good guess what it says. I'll wait for further commits to resolve those two.

**Comment by vpetersson** [comment]
@rusko124 you have any insight on this?

**Comment by rusko124** [comment]
PR Quality check should be fixed here #1208 PR
Snyk check doesn't relate with this PR(will be fix soon)
Thus we need to fix only travis CI.
FYI #1208 has changes for `.travis.yml`, please pull up the changes after merge the PR

**Comment by ekevoo** [comment]
I'm having difficulty to find the time to finish this up. In the meantime can you please reply to my question at https://github.com/Screenly/screenly-ose/pull/1180#issuecomment-515709251

**Comment by vpetersson** [comment]
@ekevoo We definitely appreciate all the effort you've put in on this. Is there anything we can do to assist you over the last hurdle? @rusko124 also please look at @ekevoo comment he referred to.

**Comment by ekevoo** [comment]
That's all I can do without the ability to test the code. 🤷‍♂️

**Comment by vpetersson** [comment]
Thanks @ekevoo. Looks like there is a merge conflict at the moment. Could you merge in master? Thanks.

**Comment by ekevoo** [comment]
I had just done exactly that 😭 but fine, it's small enough.

The two (now three) merges that I did since the initial 2to3 run didn't go through 2to3 again. Many of its transformations aren't idempotent so we can't just re-run it on every merge and further merges all require manual adjustments. However you can follow the error messages and adjust.

**Comment by vpetersson** [comment]
@rusko124 could you help out here?

**Pull request closed without merging**
