### PR TITLE
OOM and Github API error handling improvements

### PR DESCRIPTION
**Pull request by nkaminski**
This changeset improves behavior and recovery in 2 exceptional cases, namely:

- When the viewer container reaches the configure memory limit and the OOM killer is invoked, the process that is typically killed in this case is the Chromium renderer process launched by QTWebEngine causing the viewer container to continue running but display a blank white screen.  Therefore, this change increases the OOM score of the viewer container entrypoint script to the maximum value, guaranteeing that the viewer container is cleanly restarted after running OOM.

- When the Github API is unavailable or the remote branch name currently checked out in Screenly's working directory does not exist upstream, the current implementation of the update check either causes a 500 error and/or rapid requests to the GitHub API. Therefore, this change also introduces backoff logic in the event that the remote Github branch status is not available.

### CODE REVIEW

**Review by vpetersson — APPROVED** [review]
Thank you @nkaminski!

**Comment by nkaminski** [comment]
@vpetersson Would you mind adding a hacktoberfest-accepted label to this PR as well?

**Comment by vpetersson** [comment]
> @vpetersson Would you mind adding a hacktoberfest-accepted label to this PR as well?

Sure thing. Done.

**Comment by nkaminski** [comment]
I noticed this is getting marked as stale, are we good to merge or is there's something you would like changed?

**Review by vpetersson — APPROVED** [review]
LGTM - Thanks.

**Review by vpetersson — APPROVED** [review]

**Pull request merged**
