### PR TITLE
UsbAssets: friendly time format in yaml file

### PR DESCRIPTION
**Pull request by rusko124**
PR #1010
@escoand 

Before:
```
screenly:
  key: "uy7VWB4YAb638onHmW7P"
  activate: false
  copy: false
  start_date: 1553191200
  end_date: 1553796000
  duration: 10
```
Now:
```
screenly:
  key: "uy7VWB4YAb638onHmW7P"
  activate: false
  copy: false
  start_date: 03/22/2019
  end_date: 03/25/2019
  duration: 10
```

### CODE REVIEW

**Comment by escoand** [comment]
https://xkcd.com/1179/ :-p

**Comment by vpetersson** [comment]
@rusko124 yeah @escoand is right, let's stick to ISO.

**Comment by rusko124** [comment]
Got it!
Whats about the formatting for the datepicker?
datepicker

**Comment by vpetersson** [comment]
@rusko124 let's always stick to ISO for now as it gets complicated if we need to manage other formats.

**Pull request merged**
