### PR TITLE
New: UI design

### PR DESCRIPTION
**Pull request by rusko124**
PR request #1097
Screenshots:

Uploading
![5

 3.png…]()

### CODE REVIEW

**Comment by vpetersson** [comment]
Let's remove the footer in the logo. Feels a bit redundant.

**Comment by rusko124** [comment]
new-1
new-2
new-3
new-4

**Comment by rusko124** [comment]
Do I need something to change or add for the PR?

**Comment by vpetersson** [comment]
I think it looks good. Merging.

**Pull request merged**
