### PR TITLE
Update server.py

### PR DESCRIPTION
**Pull request by ealmonte32**
fix for '&' after escaping uri

### CODE REVIEW

**Comment by ealmonte32** [comment]
@vpetersson this is ready to merge , thx

**Comment by ealmonte32** [comment]
another PR that should have no objections to it being merged.. this is a fix for the escaping of the `&` character that messes up any URL that contains it.

**Comment by ealmonte32** [comment]
as mentioned in commit comments:

fixes asset name in GUI that would duplicate the `&amp;` characters indefinitely if asset with such `&` symbol was activated, deactivated, activated.. repeat and you will have multiple repeat `amp;` in the URL name...

**Comment by ealmonte32** [comment]
currently working on this because xss protection with flask escape works for what it's supposed to do, but then messes up with the naming of the asset and uri, and stores it with the escaped characters which then becomes a mess..

**Comment by martinlanger90** [comment]
Is there a workaround until it's fixed? I would like to use screenly at school on monday and therefore I need the & char.

**Comment by ealmonte32** [comment]
> Is there a workaround until it's fixed? I would like to use screenly at school on monday and therefore I need the & char.

@martinlanger90  
As of right now, after many hours and much trial and error, my best solution has been the current PR file, so until it is officially merged, if you want to have it working by tomorrow, you can just replace your current version of the `server.py` file with the one here on this PR by doing the following on the raspberry pi you're using screenly-ose on:

```
wget https://raw.githubusercontent.com/Screenly/screenly-ose/9b87b55b89c933ab5be8665b2b21d7a897190aac/server.py -O ./screenly/server.py
```

**Comment by ealmonte32** [comment]
ugh, this change from get('uri') to get('name') messes up the uploading of pictures and videos, will look into fixing that now

**Comment by ealmonte32** [comment]
new PR created with proper fixes.

**Comment by takiot** [comment]
Sorry,  bit newbie with this, but I have to ask few simple questuion. 😑

What is PR file and what do I have to do to get this fixed into my Screenly?

Run this?
wget https://raw.githubusercontent.com/Screenly/screenly-ose/b6d34a034de7cf60f51c1d42141499749ddd6f83

**Comment by ealmonte32** [comment]
> What is PR file and what do I have to do to get this fixed into my Screenly?
> 
> Run this?
> wget https://raw.githubusercontent.com/Screenly/screenly-ose/b6d34a034de7cf60f51c1d42141499749ddd6f83

PR means Pull Request.
_"Pull Requests are the heart of collaboration on GitHub. When you open a pull request, you're proposing your changes and requesting that someone review and pull in your contribution and merge them into their branch. Pull requests show diffs, or differences, of the content from both branches." Reference: https://guides.github.com/activities/hello-world/_

if you want the latest file on your current device, you download it and replace the current one in screenly folder..

`wget https://raw.githubusercontent.com/Screenly/screenly-ose/master/server.py -O /home/pi/screenly/server.py`

then restart the service:
`sudo systemctl restart screenly-web.service`

**Comment by takiot** [comment]
Thanks!

Will this fix be included in OSE-image, someday or allready?

https://github.com/screenly/screenly-ose/releases

**Comment by vpetersson** [comment]
We will build a new disk image once the improvements in the experimental branch are merged into master.

**Pull request closed without merging**
