### PR TITLE
Added option 'Skip asset check'

### PR DESCRIPTION
**Pull request by rusko124**
This option solves the problem described here #933, when user can't add asset due to server error.
For example take https://dashboard.ambientweather.net/devices/public/7034051c8592fabc11be520a5a001203 asset.
screen_1
**Without skip option:**
screen_2
**With skip option:**
screen_

### CODE REVIEW

**Comment by vpetersson** [comment]
@rusko124 I wasn't thinking about a global option, but rather a tickbox when adding an asset.

**Comment by rusko124** [comment]
single
Now it's only when add asset

**Comment by vpetersson** [comment]
Can you:

 * Change that to a checkbox
 * Make it a bit smaller

**Comment by rusko124** [comment]
edits

**Comment by vpetersson** [comment]
Yes, that's fine too. I was more thinking the alignment between the checkbox and the text, but that's solved in this design so I'm happy with that.

**Pull request merged**
