### PR TITLE
Fixes development environment

### PR DESCRIPTION
**Pull request by vpetersson**
* Bumps up base image to Buster (from Jessie)
* Applies Dockerfile best practices (and shrinks images slightly)
* Bumps up all Python libraries

### CODE REVIEW

**Comment by vpetersson** [comment]
@ealmonte32 Could you give me a review on this?

**Comment by ealmonte32** [comment]
I am far from experienced with Docker image creation but from the research and testing I've done before there are a lot of little changes I would make but I would need to take all those changes you made and merge with mine and modify them on my fork and then test and troubleshoot and compare image sizes and all that.. I just stopped working on that few weeks ago to focus on the master branch non-balena stuff because I had time and saw how outdated some things were.. this is a big task so I'll try to do it on a weekend morning or something and report the results.

**Comment by vpetersson** [comment]
I think this is a relatively safe change, so I wouldn't worry too much about it. I just wanted a second pair of eyes on it to make sure I didn't do anything silly :)

**Comment by vpetersson** [comment]
I think this is safe to merge @ealmonte32. Will need to merge it now as I need this for the work @rusko124 will do later this week.

**Comment by vpetersson** [comment]
@ealmonte32 I tested this myself just now. Had to roll back the `sh` module, but short of that, everything worked. Not too concerned with the `sh` bug as we are moving away from that particular code path shortly anyways.

**Comment by ealmonte32** [comment]
Yes that was one of the modules I originally had issues with when updating packages with pip.. I believe `subprocess` will be used instead?
Also, yes that is fine you needed to merge, if anything I can always make any changes or suggestions via PR.

**Comment by vpetersson** [comment]
> Yes that was one of the modules I originally had issues with when updating packages with pip.. I believe subprocess will be used instead?

Subprocess isn't as powerful as sh. That said, the problem at first glance appears to be related to their Python 3 upgrade. It's They have made some changes that relies on some new feature for this particular function.

I'm not to worried about it as we will drop this code when we switch to the new browser anyways.

**Pull request merged**
