### PR TITLE
Update diagnostics.py with latest Pi models

### PR DESCRIPTION
**Pull request by ealmonte32**
fixed indentation errors raised here: https://travis-ci.org/github/Screenly/screenly-ose/builds/745802167
by using [reindent.py](https://svn.python.org/projects/python/trunk/Tools/scripts/reindent.py)

### CODE REVIEW

**Comment by vpetersson** [comment]
@ealmonte32 Can you update this list while at it?

**Comment by ealmonte32** [comment]
done.

**Comment by ealmonte32** [comment]
ok finally fixed indentation issue, travis is now failing for a different reason though, something about geckodriver..
anyway this should be ready to merge.

**Comment by vpetersson** [comment]
👍

**Comment by vpetersson** [comment]
> ok finally fixed indentation issue, travis is now failing for a different reason though, something about geckodriver..
> anyway this should be ready to merge.

Ignore that error. We need to revisit the test suite anyways.

**Pull request merged**
