### PR TITLE
Feature: date format setting

### PR DESCRIPTION
**Pull request by rusko124**
Ref #1142

date_forma

### CODE REVIEW

**Comment by vpetersson** [comment]
@rusko124 looks like there are still some code quality issues.

**Comment by rusko124** [comment]
This is because script does not see the variables in the index template.
изображение

**Comment by vpetersson** [comment]
> This is because script does not see the variables in the index template.
> изображение

Fair enough.

**Comment by vpetersson** [comment]
Nice job. Merging.

**Pull request merged**
