### PR TITLE
Add missing title and update check to system info

### PR DESCRIPTION
**Pull request by daniep01**
Added player name to title and missing check for update available. I think these were lost in the move to flask.

### CODE REVIEW

**Comment by daniep01** [comment]
Not sure why travis failed, I don't think it was because of my commits.

**Comment by daniep01** [comment]
The travis check passed the second time. @vpetersson ok to merge?

**Comment by vpetersson** [comment]
@daniep01 LGTM, but @antonmolodykh can you take a look as well?

**Comment by antonmolodykh** [comment]
@vpetersson @daniep01 LGTM

**Comment by vpetersson** [comment]
Thanks, @daniep01.

**Pull request merged**
