### PR TITLE
api add get info

### PR DESCRIPTION
**Pull request by heberalmeida**
included in api device information, what is currently being loaded and size of space, to be used in external applications.

### CODE REVIEW

**Comment by vpetersson** [comment]
Thanks, @heberalmeida. Glanced over it and it seems sensible.

@antonmolodykh can you audit this PR?

Thanks.

**Comment by antonmolodykh** [comment]
@heberalmeida hmm. as far as I can see, you declare `system_uptime` and don't use it in any way.
Also, does it make sense to print systemctl logs here, if this information is on the "system info" tab?

**Comment by heberalmeida** [comment]
I did this because I needed this information because I use the api to register in multiple raspberry and this did not have in the api, in some moments I needed to see what was happening at the moment, and the amount of space available, so it includes in the api

**Comment by antonmolodykh** [comment]
@heberalmeida I tried to run it. When I send a request to the endpoint I get a server error

**Comment by heberalmeida** [comment]
@antonmolodykh I will correct

**Comment by antonmolodykh** [comment]
LGTM.
Thanks, @heberalmeida

**Pull request merged**
