### PR TITLE
Update Dockerfile.viewer

### PR DESCRIPTION
**Pull request by wmysummer**
Add open source Chinese font library to support browser to display Chinese characters

### CODE REVIEW

**Comment by vpetersson** [comment]
Thanks @wmysummer

**Comment by ealmonte32** [comment]
Good job @wmysummer , your very first pull request and it helped contribute to the viewer for all Chinese 👍🏻

**Comment by wmysummer** [comment]
> Good job @wmysummer , your very first pull request and it helped contribute to the viewer for all Chinese 👍🏻

Thanks for your help. Thank you very much.

**Comment by wmysummer** [comment]
> Thanks @wmysummer

You're welcome. It's a great honor to help with the screenly ose project. I suggest that you can set up a function to customize the amount of one-time donation to screenly ose project instead of monthly fixed donation through GitHub. I'm still looking for a job, but I also want to contribute a little.

**Comment by vpetersson** [comment]
Thanks @wmysummer. If you're able to be active on the forum and help contribute code, that would be even more helpful :)

**Pull request merged**
