### PR TITLE
Allow the user to specify the ip address for the device in screenly. …

### PR DESCRIPTION
**Pull request by jishac**
…This allows screenly to be used in "offline" mode.

### CODE REVIEW

**Comment by jishac** [comment]
Screenly is intended to work in an "offline" mode according to https://support.screenly.io/hc/en-us/articles/115002570873-Can-I-use-Screenly-OSE-in-offline-mode-

Screenly's hotspot can be disabled by creating the file .screenly/initialized and the network interfaces manually configured for local access.

However, the system will not operate without a default gateway set.  This small modification is intended to allow the user to specify a local address as the one to use for the device.  No checks are made against the user supplied address.

**Comment by antonmolodykh** [comment]
I don't quite understand why this is necessary. I mean that in fact, if there is no default gateway, you see "Unable to resolve local IP address." on your screen, and after that Screenly works as usual, that is, it displays local content. right?

**Comment by jishac** [comment]
It did not move past the splash screen, and more importantly I was unable to access the screenly web API to manage or upload content.  I would get a 500 error from the server.

**Comment by antonmolodykh** [comment]
>It did not move past the splash screen

this is because there are no local assets in your playlist (that is, the playlist is not empty, but all assets are web pages)

> I would get a 500 error from the server.

I'm not sure that this is so. the server must be started in any case. I'll check it out again tomorrow, but I'm sure it's true.
anyway, in my opinion your PR makes sense, but I can't decide how good this idea is. What do you think, @vpetersson ?

**Pull request closed without merging**
