### PR TITLE
Add reboot after installation

### PR DESCRIPTION
**Pull request by antonmolodykh**
Refs #624

### CODE REVIEW

**Comment by vpetersson** [comment]
What happens if the installation fails? Will it still reboot?

**Comment by antonmolodykh** [comment]
hmm. I'm not sure, it seems that yeah

**Comment by vpetersson** [comment]
Ok, we need to fix that then. There would be no way for the user to know if the installation failed or not. Perhaps a simple `read` would do with a 'You need to reboot the system for the installation to complete. Would you like to reboot now?'

**Comment by vpetersson** [comment]
LGTM

**Pull request merged**
