### PR TITLE
Display power

### PR DESCRIPTION
**Pull request by daniep01**
New pull request replacing #601 which was missing recent merges
Feature #585 

Here's a screenshot showing two possible versions of the info table.
systeminfo

### CODE REVIEW

**Comment by vpetersson** [comment]
Great! Thanks. Can we just make a minor tweak and change it to 'Display Power: On/Off' instead? That feels like a more natural way to describe the state.

**Comment by daniep01** [comment]
Yes, will change the wording. Any thoughts on the table layout?

**Comment by vpetersson** [comment]
Awesome. Thanks, @daniep01.

@antonmolodykh can you take a look as well as a second pair of eyes?

**Comment by antonmolodykh** [comment]
LGTM

**Pull request merged**
