### PR TITLE
Preparation of migration celery branch into master branch

### PR DESCRIPTION
**Pull request by rusko124**
Edits:
- Change celery broker to rabbitmq (Reason: a bunch of python2.7 + celery4 + redis(raspbian) is not working now, but it was good before. I was looking for a solution, but at the moment without success)
- Fix: pass environments vars to ansible-playbook (Since we need to now run ansible-playbook with sudo)
- Added the feature of setup a new pi password when updating from console.
- Visual edits: update logs from UI has a terminal style.
progress_upgrade
- Fix: added `systemctl` and `wifi-connect` to whitelist.
- Small edit: sorting settings( From simple to more dangerous(e.g. system commands))

**PS: The PR in progress. At the moment I working on full testing of the Celery branch(including updates to other version of Screenly and back, and balena). So I'll let you know when the testing is over.**

### CODE REVIEW

**Comment by rusko124** [comment]
Updated:
- Some edits to code quality
- User friendly auto-scroll of upgrade logs
- Added notice text to upgrade popup
notice
- `Update Available` button navigates to upgrade button of settings page
- Cleanup in the repo
- Hide some feature on balena
- Some edits for dockerfiles

Tests were reproduced:
- Upgraded master(celery) to experimental from console
- Upgraded experimental to master(celery) from console
- Installed on Balena
- USB assets function works
- System controls(reboot and shutdown) function works
- Upgraded from UI function works
- Backup works on all versions

@vpetersson Did I miss anything?

**Comment by vpetersson** [comment]
How do we get USB assets to work inside of Docker?

**Comment by rusko124** [comment]
We didn't add this feature to Docker

**Comment by vpetersson** [comment]
If we don't have this feature - how come it's listed above in your list?

**Comment by rusko124** [comment]
The feature is directly on the device. We don't use Docker there.

**Comment by rusko124** [comment]
Screenshots with new design:
celery-1
celery-2
celery-3
celery-4

**Comment by rusko124** [comment]
Last edits:
- Merge with master
- Code quality fixes
- Small design fixes
- Edits for `def system_info`
- Updated list of Raspberry model(Added new versions)
- Uncommited the part of code for merge to master

Reasons why checks have not passed:
- Snyk: requirements.txt was moved to `requirements` dir. Manifest not found.
- Codacy: `Function has a complexity of 5` defines on a function that is not.

**Comment by rusko124** [comment]
@vpetersson  I think yes but before merging, please review `./bin/install.sh` and perhaps quick look to ansible tasks. I tested everything on a real device and that works well, but maybe there is something with which you do not agree.

**Pull request merged**
