### PR TITLE
Add column 'duration' to asset row

### PR DESCRIPTION
**Pull request by rusko124**
These edits for #818.
Also "duration" column, can be done as an option in the settings.

display_asset_duration

### CODE REVIEW

**Comment by rusko124** [comment]
I think we can do option selection fields that are needed in the settings. This will enable hide for example Start date and End date, but show only the duration.
What are you think? @vpetersson

**Comment by vpetersson** [comment]
@rusko124 please add the (time) unit for the duration too.

**Comment by rusko124** [comment]
col_duration

**Comment by rusko124** [comment]
duration

**Comment by vpetersson** [comment]
Nice!

**Pull request merged**
