### PR TITLE
Added 'Raspberry Model' and 'Screenly version' for system info page

### PR DESCRIPTION
**Pull request by rusko124**
Discussion #971
system_info

### CODE REVIEW

**Comment by vpetersson** [comment]
@rusko124 Wouldn't this break in the new Celery branch? How do you want to solve that?

**Comment by rusko124** [comment]
> @rusko124 Wouldn't this break in the new Celery branch? How do you want to solve that?

In Screenly Version column is set current_branch@short_git_hash
One edit if the `master` branch then it will be set to `development` text(For more understanding).

I do not know what exactly to set in this column, this is just an example for now. Could you help me with this? @vpetersson

**Comment by bcherup** [comment]
Will this used in experimental ?

**Comment by rusko124** [comment]
@vpetersson  
What needs to be added or changed to progress here?

**Pull request merged**
