### PR TITLE
Date time locale setting

### PR DESCRIPTION
**Pull request by daniep01**
#599 
First attempt, doesn't automatically detect locale yet.

### CODE REVIEW

**Comment by vpetersson** [comment]
@daniep01 interesting approach. The issue with reading the locale from the system (rather than the browser), is that it will often time be wrong. For instance, if someone installs Screenly using NOOBS, chances are they will not bother updating the locale on the system. 

As such, I think it makes more sense to read it from the browser using some kind of JS framework.

**Comment by daniep01** [comment]
That would be ideal but it seems to be a bit of a minefield. It looks like there is no consistent way that is guaranteed to work across browsers.
[https://zzz.buzz/2016/01/13/detect-browser-language-in-javascript/](url)
Do you know of any specific bit of framework that we could use?

**Comment by vpetersson** [comment]
@petermonte Do you have any recommendations here?

**Comment by petermonte** [comment]
@vpetersson and @daniep01,

I would recommend this **[answer](https://stackoverflow.com/questions/10659523/how-to-get-the-exact-local-time-of-client#answer-39161134)** on **Stackoverflow**. 

While working in several apps that make use of local time I've found **[moment.js](https://momentjs.com/)** to be a robust JS framework. It holds several methods to use and manipulate time and also includes a complete library for locale strings and time format.

Now this goes without saying that using the browser time will always be dependent of the system time, which by the way is completely vulnerable to user manipulation. Once I change my system time my web app suffers the same change.

To really get a precise time I would say that the use of a **[server](https://time.is/)** API holding time combined with bowser time interval would be the case. Check **[time.is](https://time.is/)** and change your local system time. You will see a moment where the time changes in the browser but in a matter of a second it gets corrected.

Hope this help.

**Comment by antonmolodykh** [comment]
Given @petermonte comment and the fact that Screenly should also work without connection, in my opinion unfortunately this PR now does not make sense

**Pull request closed without merging**
