### PR TITLE
Patch for compiling experimental build on Resin

### PR DESCRIPTION
**Pull request by brandfocus**

### CODE REVIEW

**Comment by vpetersson** [comment]
Very nice @brandfocus. Could you take a look @rusko124?

**Comment by brandfocus** [comment]
There are still issues starting the viewer that I have been unable to resolve @rusko124 but this at least gets all the way to the build compiling and the container running on the device.

**Comment by rusko124** [comment]
@vpetersson  I tested this patch, I confirm that it works. Good job @brandfocus . I'll try to start working on the issue with viewer in the near future.

**Comment by vpetersson** [comment]
@brandfocus Could you elaborate on the issues that you are still experiencing?

**Comment by brandfocus** [comment]
@vpetersson I don't have a device in front of me to test straight away but it was along the lines of registering the Qt session

**Comment by vpetersson** [comment]
Does it just throw an error or prevent it from load entirely?

**Comment by brandfocus** [comment]
@vpetersson Prevents the load entirely...

**Comment by brandfocus** [comment]
@vpetersson @rusko124 were you able to reproduce this?

**Comment by vpetersson** [comment]
@brandfocus We're working on the tasks in Sprint 8 right now. I'll add this to Sprint 9.

**Pull request closed without merging**
