### PR TITLE
Remove unused assets

### PR DESCRIPTION
**Pull request by antonmolodykh**
Removed unused resources and renamed wireload-bg.jpeg into screenly-bg.jpeg

Refs https://github.com/Screenly/screenly-ose/issues/581

### CODE REVIEW

**Comment by vpetersson** [comment]
I'm not sure `static/img/drag-handle@2x.png` should be deleted if the file `static/img/drag-handle.png` exists.

**Comment by antonmolodykh** [comment]
@vpetersson I checked: we really don't use this picture

**Comment by vpetersson** [comment]
@antonmolodykh hmm should we not fix the `@2x` issue then?

**Comment by antonmolodykh** [comment]
@vpetersson you mean just leave `drag-handle@2x.png` ?

**Comment by vpetersson** [comment]
@petermonte Could you point @antonmolodykh in the right direction here?

**Comment by petermonte** [comment]
@vpetersson and @antonmolodykh,

In fact `drag-handle@2x.png` is not being used [here](https://github.com/Screenly/screenly-ose/blob/87b59815255b9aa1b09f2a327bfd988a181b796e/views/index.haml#L65). But this doesn't mean we should remove it.

What needs to be done is either point css to use the `@2x` under a media query for higher DPI screens or take advantage of the `srcset` attribute for `img` tags. You can find [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Example_3_Using_the_srcset_attribute) some good documentation

**Comment by antonmolodykh** [comment]
@petermonte understand, thank you :)

**Pull request merged**
